runtime: python310
runtime_config:
  python_version: 3.10
handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
  expiration: 1s
# - url: /(.*)
#   static_files: build/\1
#   upload: build/(.*)

# Catch-all: send all other requests to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always
  expiration: "1s"