runtime: python27
api_version: 1
threadsafe: true
runtime_config:
  python_version: 3.12
handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
  expiration: 1s
- url: /(.*)
  static_files: build/\1
  upload: build/(.*)