name: Deploy Staging Frontend

on:
  push:
    branches: [main]

jobs:

  dev-deploy:
    if: github.repository == 'CATALOG-Historic-Records/orphaned-wells-ui'
    name: Deploy to Google App Engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
            credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}'

      - name: Install packages
        run: |
            npm clean-install
      
      - name: Add .env file
        run: |
            echo REACT_APP_BACKEND_URL=\"${{ secrets.DEV_BACKEND_URL }}\" >> .env

      - name: Build frontend
        env:
          CI: false
        run: |
            npm run build

      - name: Deploy
        run: |
            gcloud app deploy