name: App Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

defaults:
  run:
    # -l: use login shell (required when using Conda)
    shell: bash -l {0}

env:
  PYTEST_ADDOPTS: --color=yes

jobs:
  component-tests:
    name: Component testing (${{ matrix.os }})

    runs-on: ${{ matrix.os-version }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - linux
          - win64
        include:
          - os: linux
            os-version: ubuntu-latest
          - os: win64
            os-version: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Electron JS dependencies
        run: |
          npm clean-install
          
    #   - name: run frontend
    #     run: npm start & sleep 30

      - name: run component tests
        run: npm test
