name: Deploy Staging Frontend

on:
  push:
    branches: [add-testing]
  pull_request:
    branches: [main]

jobs:

  staging-deploy:
    name: Deploy to Google App Engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
            credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}'

      - name: Install packages
        run: |
            npm clean-install
      
      - name: Add backend url to .env file
        run: |
            echo REACT_APP_BACKEND_URL=${{ secrets.DEV_BACKEND_URL }} >> .env
    
      - name: print
        run: |
            cat .env